/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view.user;

import org.example.controllers.BookingController;
import org.example.dependencyInjection.BookingControllerFactory;
import org.example.dtos.BookingDetail;

/**
 *
 * @author fadhl
 */
public class BookingStrukView extends javax.swing.JFrame {
    private BookingControllerFactory bookingControllerFactory = new BookingControllerFactory();
    private BookingController bookingController = bookingControllerFactory.controller();
    private String bookingKode;
    public BookingStrukView() {
        initComponents();
        setStruk();
    }
    public BookingStrukView(String bookingKode){
        this.bookingKode = bookingKode;
        initComponents();
        setStruk();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBookingKode = new javax.swing.JLabel();
        lblVenueKode = new javax.swing.JLabel();
        lblVenueName = new javax.swing.JLabel();
        lblDateOrder = new javax.swing.JLabel();
        lblDateBooked = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblBookingKode1 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        lblEnd1 = new javax.swing.JLabel();
        lblStart1 = new javax.swing.JLabel();
        lblDateBooked1 = new javax.swing.JLabel();
        lblVenueName1 = new javax.swing.JLabel();
        lblVenueKode1 = new javax.swing.JLabel();
        lblDateOrder1 = new javax.swing.JLabel();
        lblEnd2 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Struk Pemesanan");

        jLabel1.setText("======================================================");

        jLabel2.setText("======================================================");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ABC SPORT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Bukti Pemesanan Lapangan");

        lblBookingKode.setText("kode Booking");

        lblVenueKode.setText("Kode Lapangan");

        lblVenueName.setText("Nama Lapangan");

        lblDateOrder.setText("Tgl Transaksi");

        lblDateBooked.setText("Tgl Pemesanan");

        lblStart.setText("Mulai");

        lblEnd.setText("Selesai");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total ");

        lblBookingKode1.setText("kode Booking");

        lblTotal1.setText("Total ");

        lblEnd1.setText("Selesai");

        lblStart1.setText("Mulai");

        lblDateBooked1.setText("Tgl Pemesanan");

        lblVenueName1.setText("Nama Lapangan");

        lblVenueKode1.setText("Kode Lapangan");

        lblDateOrder1.setText("Tgl Transaksi");

        lblEnd2.setText("Status");

        lblStatus.setText("Berhasil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblDateOrder1)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel4)))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBookingKode1)
                    .addComponent(lblTotal1)
                    .addComponent(lblEnd1)
                    .addComponent(lblStart1)
                    .addComponent(lblDateBooked1)
                    .addComponent(lblVenueName1)
                    .addComponent(lblVenueKode1)
                    .addComponent(lblEnd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBookingKode)
                    .addComponent(lblVenueKode)
                    .addComponent(lblVenueName)
                    .addComponent(lblDateBooked)
                    .addComponent(lblStart)
                    .addComponent(lblEnd)
                    .addComponent(lblTotal)
                    .addComponent(lblStatus))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOrder)
                    .addComponent(lblDateOrder1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblBookingKode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVenueKode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVenueName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDateBooked)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBookingKode1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVenueKode1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVenueName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDateBooked1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStart1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingStrukView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingStrukView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingStrukView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingStrukView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingStrukView().setVisible(true);
            }
        });
    }
    private void setStruk(){
        String status = "";
        BookingDetail bookingDetail = bookingController.reportBookingStruck(this.bookingKode);
        lblDateOrder.setText(bookingDetail.getDateOrder());
        lblDateBooked.setText(bookingDetail.getDateBooked());
        lblBookingKode.setText(bookingDetail.getBookedId());
        lblVenueKode.setText(bookingDetail.getVenueId());
        lblVenueName.setText(bookingDetail.getVenueName());
        lblStart.setText(bookingDetail.getStartTime());
        lblEnd.setText(bookingDetail.getEndTime());
        lblTotal.setText(bookingDetail.getPrice().toString());
        if (bookingDetail.isConfirmed() == null){
            status = "Belum Terkonfirmasi";
        } else if (bookingDetail.isConfirmed() == true) {
            status = "Berhasil";
        } else if (bookingDetail.isConfirmed() == false) {
            status = "Ditolak";
        }
        lblStatus.setText(status);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBookingKode;
    private javax.swing.JLabel lblBookingKode1;
    private javax.swing.JLabel lblDateBooked;
    private javax.swing.JLabel lblDateBooked1;
    private javax.swing.JLabel lblDateOrder;
    private javax.swing.JLabel lblDateOrder1;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblEnd1;
    private javax.swing.JLabel lblEnd2;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblStart1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblVenueKode;
    private javax.swing.JLabel lblVenueKode1;
    private javax.swing.JLabel lblVenueName;
    private javax.swing.JLabel lblVenueName1;
    // End of variables declaration//GEN-END:variables
}
