package admin.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import org.example.controllers.BookingController;
import org.example.dependencyInjection.BookingControllerFactory;
import org.example.dtos.BookingDetail;
import org.example.exceptions.WarningException;
import org.example.services.impl.ReportService;

public class form_stok extends javax.swing.JPanel {
    private ReportService reportService = new ReportService();
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form form_stok
     */
    public form_stok() {
        initComponents();
         datatable();
    }

    protected void datatable(){
        Object[] Baris ={"Kode Barang","Nama Barang","Jenis","Stok","Lapangan"};
        tabmode = new DefaultTableModel (null, Baris);
        inventory.setModel(tabmode);
        String sql = "select * FROM inventory";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kode");
                String b = hasil.getString("nama");
                String c = hasil.getString("jenis");
                String d = hasil.getString("stok");
                String e = hasil.getString("lapangan");

            String[] data={a,b,c,d,e};
            tabmode.addRow(data);
        }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new javax.swing.JPanel();
        stokBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventory = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        mainPanel1.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel1.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel1.setLayout(new java.awt.CardLayout());

        stokBarang.setBackground(new java.awt.Color(255, 255, 255));
        stokBarang.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LAPORAN STOK");

        btnPrint.setBackground(new java.awt.Color(0, 102, 153));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        btnPrint.setText("Cetak");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inventory);

        javax.swing.GroupLayout stokBarangLayout = new javax.swing.GroupLayout(stokBarang);
        stokBarang.setLayout(stokBarangLayout);
        stokBarangLayout.setHorizontalGroup(
            stokBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(stokBarangLayout.createSequentialGroup()
                .addGroup(stokBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        stokBarangLayout.setVerticalGroup(
            stokBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stokBarangLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnPrint)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        mainPanel1.add(stokBarang, "card2");

        add(mainPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
            HashMap params = new HashMap<>();
            reportService.print("report_stok.jasper", params);
            return;
    }//GEN-LAST:event_btnPrintActionPerformed

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked

    }//GEN-LAST:event_inventoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JTable inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JPanel stokBarang;
    // End of variables declaration//GEN-END:variables
}
